void check_pit();
unsigned int get_system_ns();
unsigned int get_system_us();
unsigned int get_system_ms();
unsigned int get_system_se();
void nstime();
void ustime();
void mstime();
void time();
void cnstime();
void custime();
void cmstime();
void ctime();
